(ns vehiclesale.render-html
  "Build-time SPA for the used-car marketplace (Carsensor-like search) plus
  the operator console. One document, fragment views (`#search` / `#v/<vin>`
  / `#account` / `#inbox` / `#list` / `#operator`). Generated by driving the
  real OperationActor (VehicleSale-LLM ⊣ VehicleSaleGovernor ⊣ store).

  Usage: `clojure -M:dev:render-html [out-file]`
  Default writes `docs/samples/operator-console.html` and also `docs/index.html`
  (same bytes — one SPA, two entry paths)."
  (:require [clojure.java.io :as io]
            [clojure.set :as set]
            [clojure.string :as str]
            [jp-go-dds.core :as dds]
            [jp-go-dds.page :as page]
            [jp-go-dds.tokens :as tokens]
            [langgraph.graph :as g]
            [vehiclesale.body :as body]
            [vehiclesale.border :as border]
            [vehiclesale.catalog :as catalog]
            [vehiclesale.commerce :as commerce]
            [vehiclesale.operation :as op]
            [vehiclesale.policy :as policy]
            [vehiclesale.store :as store]
            [vehiclesale.x402 :as x402]))

(def ^:private dealer {:actor-id "da-1" :actor-role :dealer-agent :phase 3})
(def ^:private officer {:actor-id "to-1" :actor-role :title-officer :phase 3})
(def ^:private buyer {:actor-id "b-1" :actor-role :buyer :tenant "tenant-basic" :phase 3})

(def jp-airis
  {:class :operator-licensed-shakensho-feed
   :ref "airis-demo:JP-100"
   :license-id "airis-demo"})

(defn- exec! [actor tid request context]
  (g/run* actor {:request request :context context} {:thread-id tid}))

(defn- approve! [actor tid]
  (g/run* actor {:approval {:status :approved :by "officer-1"}}
          {:thread-id tid :resume? true}))

(defn- jp-list
  [vin extra]
  (let [seed (get-in (store/demo-data) [:vehicles vin])]
    (merge {:op :vehicle/list :subject vin :vin vin
            :source (assoc jp-airis :ref (str "airis-demo:" vin))}
           seed
           extra)))

(defn run-demo!
  "Fresh seed through a mix of marketplace writes and every HARD gate.
  Returns the store. Every field the page reads comes from this run."
  []
  (let [db (store/seed-db)
        actor (op/build db)]
    ;; US: authorized listing commits (odometer bump).
    (exec! actor "us-list"
           {:op :vehicle/list :subject "vin-100" :vin "vin-100" :make "Demo"
            :model "Sedan" :year 2022 :title-status :clean :price 18500.00M
            :odometer 33500 :state :ca
            :source {:class :federal-title-registry :ref "nmvtis-doj-gateway:vin-100"}}
           dealer)
    ;; HARD: rbac
    (exec! actor "rbac"
           {:op :vehicle/list :subject "vin-100" :vin "vin-100" :make "Demo"
            :model "Sedan" :year 2022 :title-status :clean :price 18500.00M
            :odometer 33600 :state :ca
            :source {:class :federal-title-registry :ref "nmvtis-doj-gateway:vin-100"}}
           buyer)
    ;; HARD: source-provenance (unsourced)
    (exec! actor "unsourced"
           {:op :vehicle/list :subject "vin-100" :vin "vin-100" :make "Demo"
            :model "Sedan" :year 2022 :title-status :clean :price 18500.00M
            :odometer 33700 :state :ca
            :source {:class :federal-title-registry :ref "demo"} :unsourced? true}
           dealer)
    ;; HARD: lien-clearance
    (exec! actor "lien"
           {:op :sale/confirm :subject "vin-200" :vin "vin-200"
            :lien-cleared? false :odometer-disclosure-statement? true}
           dealer)
    ;; HARD: licensed-disclosure
    (exec! actor "greedy"
           {:op :disclosure/query :subject "vin-100" :vin "vin-100" :greedy? true}
           buyer)
    ;; HARD: odometer rollback
    (exec! actor "rollback"
           {:op :vehicle/list :subject "vin-300" :vin "vin-300" :make "Demo"
            :model "Hatchback" :year 2019 :title-status :salvage :price 6200.00M
            :odometer 50000 :state :ca
            :source {:class :federal-title-registry :ref "nmvtis-doj-gateway:vin-300"}}
           dealer)
    ;; HARD: 古物商許可欠落
    (exec! actor "no-kobutsusho"
           (jp-list "JP-100" {:kobutsusho-license "" :odometer 32100})
           dealer)
    ;; HARD: 修復歴未開示
    (exec! actor "no-repair-hist"
           {:op :sale/confirm :subject "JP-400" :vin "JP-400" :lien-cleared? true}
           dealer)
    ;; HARD: inquiry against missing VIN
    (exec! actor "ghost-inq"
           {:op :inquiry/submit :subject "JP-ghost" :vin "JP-ghost"
            :buyer-id "buyer-demo" :body "この車の現車確認はできますか" :inquiry-id "inq-ghost"}
           buyer)
    ;; HARD: 必須カメラ角不足 (JP-500 seed は :front のみ)
    (exec! actor "short-scan"
           (jp-list "JP-500" {:odometer 120000})
           dealer)
    ;; HARD: 車検切れ成約
    (exec! actor "expired-shaken"
           {:op :sale/confirm :subject "JP-300" :vin "JP-300"
            :lien-cleared? true :repair-history-disclosed? true}
           dealer)
    ;; HARD: x402 レシートが導出できない (payer 欠落)
    (exec! actor "x402-nopayer"
           {:op :x402/unlock :subject "JP-100" :vin "JP-100"
            :resource :scan-pack}
           buyer)
    ;; HARD: 精算プランが保存則を満たさない
    (exec! actor "bad-plan"
           {:op :escrow/open :subject "JP-100" :vin "JP-100"
            :buyer-id "buyer-demo"
            :plan {:plan/gross-yen 100 :plan/commission-yen 50
                   :plan/seller-payout-yen 10 :plan/conserved? false}}
           dealer)
    ;; HARD: 未検証の払出先 (デモ自動車札幌)
    (exec! actor "unverified-payout"
           {:op :escrow/open :subject "JP-500" :vin "JP-500"
            :buyer-id "buyer-demo"}
           dealer)
    ;; HARD: キャプチャ無し + 未納車 + 送金実行の主張
    (exec! actor "release-too-soon"
           {:op :escrow/propose-release :subject "JP-100" :vin "JP-100"
            :escrow-id "esc-missing" :already-transferred? true}
           officer)
    ;; JP listing commit ( legit 古物商 + AIRIS + 完了スキャン )
    (exec! actor "jp-list"
           (jp-list "JP-100" {:odometer 32100})
           dealer)
    ;; conserved escrow + 預かり更新 (認可のみ。送金しない)
    (exec! actor "esc-open"
           {:op :escrow/open :subject "JP-200" :vin "JP-200"
            :buyer-id "buyer-demo"}
           dealer)
    (exec! actor "custody-lot"
           {:op :custody/transfer :subject "JP-200" :vin "JP-200"
            :status :at-lot :holder "デモオート大阪"}
           dealer)
    ;; buyer inquiry commit
    (exec! actor "jp-inq"
           {:op :inquiry/submit :subject "JP-200" :vin "JP-200"
            :buyer-id "buyer-demo" :body "試乗希望です" :inquiry-id "inq-JP-200"}
           buyer)
    ;; HARD: inquiry reply by a stranger
    (exec! actor "stranger-reply"
           {:op :inquiry/reply :subject "inq-JP-200" :inquiry-id "inq-JP-200"
            :body "当事者ではない返信" :by "stranger"}
           {:actor-id "stranger" :actor-role :buyer :tenant "tenant-basic" :phase 3})
    ;; HARD: live buyer escrow against seed/demo stock
    (exec! actor "demo-buy"
           {:op :escrow/open :subject "JP-100" :vin "JP-100"
            :buyer-id "b-1" :channel :live}
           buyer)
    ;; JP sale with 修復歴 disclosed → sold
    (exec! actor "jp-sold"
           {:op :sale/confirm :subject "JP-400" :vin "JP-400"
            :lien-cleared? true :repair-history-disclosed? false}
           dealer)
    ;; salvage US sale escalates then human approves
    (let [r (exec! actor "salvage"
                    {:op :sale/confirm :subject "vin-300" :vin "vin-300"
                     :lien-cleared? true :odometer-disclosure-statement? true}
                    dealer)]
      (when (= :interrupted (:status r))
        (approve! actor "salvage")))
    ;; HARD: unknown ISO (not a duty invention)
    (exec! actor "unknown-iso"
           {:op :sale/confirm :subject "JP-100" :vin "JP-100"
            :lien-cleared? true :repair-history-disclosed? true
            :dest-country :xx}
           dealer)
    ;; HARD: denied destination fixture :zz
    (exec! actor "denied-zz"
           {:op :sale/confirm :subject "JP-100" :vin "JP-100"
            :lien-cleared? true :repair-history-disclosed? true
            :dest-country :zz}
           dealer)
    ;; HARD: RHD → LHD without waiver (JP → US)
    (exec! actor "steering"
           {:op :sale/confirm :subject "JP-100" :vin "JP-100"
            :lien-cleared? true :repair-history-disclosed? true
            :dest-country :us :export-certified? true :import-permit? true}
           dealer)
    ;; HARD: export certificate missing (JP → AU, both RHD)
    (exec! actor "no-export"
           {:op :sale/confirm :subject "JP-200" :vin "JP-200"
            :lien-cleared? true :repair-history-disclosed? true
            :dest-country :au}
           dealer)
    ;; HARD: import permit missing (export claimed)
    (exec! actor "no-import"
           {:op :sale/confirm :subject "JP-200" :vin "JP-200"
            :lien-cleared? true :repair-history-disclosed? true
            :dest-country :gb :export-certified? true}
           dealer)
    ;; HARD: Singapore ARF/OMV uncomputable
    (exec! actor "sg-uncomputable"
           {:op :sale/confirm :subject "JP-100" :vin "JP-100"
            :lien-cleared? true :repair-history-disclosed? true
            :dest-country :sg :export-certified? true :import-permit? true}
           dealer)
    ;; HARD: manufactured landed total
    (exec! actor "fake-tariff"
           {:op :border/quote :subject "JP-100" :vin "JP-100"
            :dest-country :de
            :quote {:landed/computable? true :landed/total-minor 1
                    :landed/customs-value-minor 1 :landed/duty-minor 0
                    :landed/vat-minor 0 :landed/conserved? true}}
           dealer)
    ;; HARD: self-adjudicated HS
    (exec! actor "hs-adj"
           {:op :border/quote :subject "JP-100" :vin "JP-100"
            :dest-country :de
            :hs {:hs "870323" :adjudicated? true}}
           dealer)
    ;; HARD: KS 1515 age cap (JP-500 2016 → Kenya)
    (exec! actor "ke-age"
           {:op :sale/confirm :subject "JP-500" :vin "JP-500"
            :lien-cleared? true :repair-history-disclosed? true
            :dest-country :ke :export-certified? true :import-permit? true}
           dealer)
    ;; HARD: AU used-import SEVS/RAWS (duty exists; regime does not)
    (exec! actor "au-sevs"
           {:op :sale/confirm :subject "JP-100" :vin "JP-100"
            :lien-cleared? true :repair-history-disclosed? true
            :dest-country :au :export-certified? true :import-permit? true}
           dealer)
    ;; HARD: Chile Ley 18.483 mainland used-import (duty exists; regime does not)
    (exec! actor "cl-ley18483"
           {:op :border/quote :subject "JP-100" :vin "JP-100"
            :dest-country :cl}
           dealer)
    ;; ZOFRI re-export: exception, Chilean duty/VAT 0, onward duty is a gap
    (exec! actor "cl-zofri"
           {:op :border/quote :subject "JP-100" :vin "JP-100"
            :dest-country :cl :zofri-reexport? true}
           dealer)
    ;; Mongolia: RHD accepted, 5%+10% computable, excise is a gap
    (exec! actor "mn-quote"
           {:op :border/quote :subject "JP-100" :vin "JP-100"
            :dest-country :mn}
           dealer)
    ;; HARD: South Africa ITAC used-import (duty exists; regime does not)
    (exec! actor "za-itac"
           {:op :border/quote :subject "JP-100" :vin "JP-100"
            :dest-country :za}
           dealer)
    ;; Durban RIB transit: exception, SA duty/VAT 0, onward duty is a gap
    (exec! actor "za-rib"
           {:op :border/quote :subject "JP-100" :vin "JP-100"
            :dest-country :za :rib-transit? true}
           dealer)
    ;; HARD: Sri Lanka Gazette 2421/04 three-year manufacture cap
    (exec! actor "lk-age"
           {:op :border/quote :subject "JP-100" :vin "JP-100"
            :dest-country :lk}
           dealer)
    ;; HARD: DE listing without dealer licence
    (exec! actor "no-dealer-lic"
           (merge (get-in (store/demo-data) [:vehicles "DE-100"])
                  {:op :vehicle/list :subject "DE-100" :vin "DE-100"
                   :dealer-license "" :odometer 42000
                   :source {:class :operator-licensed-eu-type-feed
                            :ref "eu-type-demo:DE-100"
                            :license-id "eu-type-demo"}})
           dealer)
    db))

(defn- listings [db]
  (mapv (fn [v]
          (catalog/hydrate v (store/odometer-latest db (:vin v))
                           (store/title-record db (:vin v))))
        (store/all-vehicles db)))

(defn- hold-facts [db]
  (filterv #(= :policy-hold (:t %)) (store/ledger db)))

(defn- exercised-hard-rules [db]
  (into #{} (mapcat :basis (hold-facts db))))

(def ^:private app-css
  (str tokens/bridge-css "\n" tokens/a11y-css "\n"
       (str/join "\n"
                 [".site-nav{display:flex;gap:0.5rem;flex-wrap:wrap;margin:0 0 1.5rem}"
                  ".view{display:none}"
                  ".view.is-active{display:block}"
                  ".listing-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(16rem,1fr));gap:1rem}"
                  ".listing-card{display:block;text-decoration:none;color:inherit}"
                  ".listing-card .price{font-size:1.25rem;font-weight:700;color:var(--color-key-900)}"
                  ".listing-card .meta{color:var(--color-neutral-solid-gray-600);font-size:0.875rem}"
                  ".listing-card.is-hidden{display:none}"
                  ".spec-dl{display:grid;grid-template-columns:8rem 1fr;gap:0.25rem 1rem}"
                  ".spec-dl dt{color:var(--color-neutral-solid-gray-600)}"
                  ".scan-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(8rem,1fr));gap:0.5rem;margin:0.75rem 0}"
                  ".scan-cell{padding:0.5rem;border:1px solid var(--color-neutral-solid-gray-200);font-size:0.875rem}"
                  ".scan-cell.is-missing{opacity:0.55}"
                  ".filter-row{display:flex;flex-wrap:wrap;gap:0.75rem;align-items:flex-end;margin:0 0 1rem}"
                  ".filter-row label{display:flex;flex-direction:column;font-size:0.875rem;gap:0.25rem}"
                  ".muted{color:var(--color-neutral-solid-gray-600)}"
                  ".badge{display:inline-block;margin:0 0.25rem 0 0;padding:0.1rem 0.4rem;border:1px solid var(--color-neutral-solid-gray-200);font-size:0.75rem}"
                  ".live-form{display:flex;flex-direction:column;gap:0.5rem;max-width:24rem;margin:0 0 1.5rem}"
                  ".needs-serve{display:none}"
                  "body.is-live .needs-serve{display:block}"
                  "body.is-live form.live-form.needs-serve{display:flex}"
                  "body.is-live .needs-file{display:none}"
                  ".live-form label{display:flex;flex-direction:column;gap:0.25rem;font-size:0.875rem}"
                  ".ok{color:var(--color-success-900,#0b7a3b)}"
                  ".critical{color:var(--color-error-900,#c52828)}"
                  ".warn{color:var(--color-warning-900,#8a5a00)}"])))

(defn- card-el [listing]
  (let [c (catalog/card listing)]
    [:a {:class "listing-card dds-ext-card"
         :href (:href c)
         :data-vin (:vin listing)
         :data-make (:make listing)
         :data-prefecture (some-> (:prefecture listing) name)
         :data-year (str (:year listing))
         :data-price (str (or (catalog/price-jpy listing) 0))
         :data-mileage (str (:mileage listing))
         :data-body (some-> (:body-type listing) name)
         :data-country (name (or (:country listing) (:jurisdiction listing) :na))
         :data-export (catalog/export-dest-tokens listing)
         :data-q (str (:make listing) " " (:model listing) " " (:grade listing) " "
                      (get catalog/prefectures (:prefecture listing)) " "
                      (:country-label listing))}
     (dds/heading 3 (:title c) {:size "20"})
     [:p {:class "price"} (:price c)]
     [:p {:class "meta"}
      (str (:year c) " · " (:mileage c) " · " (:prefecture c)
           (when (:country c) (str " · " (:country c))))]
     [:p {:class "meta"}
      (str (:body c) " · " (:fuel c) " · " (:repair-history c))]
     [:p {:class "meta"}
      (str (when (:annual-cost c) (str "維持費概算 " (:annual-cost c) " · "))
           (if (:scan-complete? c) "スキャン完了" "スキャン不足"))]
     [:p {:class "meta"}
      (when (:demo? c) [:span {:class "badge"} "デモ在庫"])
      (when (= :private-party (:listing-kind c)) [:span {:class "badge"} "自己申告"])
      (:dealer c)]]))

(defn- spec-row [k v]
  (when v
    (list [:dt k] [:dd (str v)])))

(defn- scan-cells [listing]
  (let [present (body/present-angles (:scan listing))]
    (map (fn [angle]
           [:div {:class (str "scan-cell" (when-not (contains? present angle) " is-missing"))}
            [:div (get body/angle-labels angle (name angle))]
            [:div {:class "muted"}
             (if (contains? present angle) "撮影済み（デモCID）" "未撮影")]])
         (sort body/required-angles))))

(defn- x402-rows []
  (mapv (fn [{:keys [id usd description]}]
          [(name id) (str "$" usd " USDC") description])
        x402/resources))

(defn- cost-rows [est]
  (when est
    [["自動車税" (catalog/yen (:automobile-tax-yen est))]
     ["重量税（年割）" (catalog/yen (:weight-tax-yen est))]
     ["燃料" (catalog/yen (:fuel-yen est))]
     ["車検償却" (catalog/yen (:shaken-yen est))]
     ["自賠責（年割）" (catalog/yen (:compulsory-insurance-yen est))]
     ["任意保険（仮定）" (catalog/yen (:voluntary-insurance-yen est))]
     ["合計（概算）" (catalog/yen (:total-yen est))]]))

(defn- quote-rows [listing]
  (mapv (fn [q]
          [(name (:landed/dest q))
           (str (:landed/hs q))
           (catalog/money (:landed/customs-value-minor q) (:landed/currency q))
           (str (/ (:landed/duty-bps q) 100.0) "%")
           (catalog/money (:landed/duty-minor q) (:landed/currency q))
           (catalog/money (:landed/vat-minor q) (:landed/currency q))
           (catalog/money (:landed/total-minor q) (:landed/currency q))])
        (border/quotes-from listing)))

(defn- corridor-rows [listing]
  (mapv (fn [{:keys [rank iso label units note in-table? eligible?
                     eligibility-reason landed-computable? landed-missing omit-reason]}]
          [(str rank)
           (str label " (" (name iso) ")")
           (catalog/grouped-int units)
           (cond (not in-table?) (str "市場表に無い: " (name (or omit-reason :n-a)))
                 eligible? "適格"
                 :else (name (or eligibility-reason :n-a)))
           (cond (not in-table?) "—"
                 landed-computable? "概算可"
                 :else (name (or landed-missing :n-a)))
           (str note)])
        (border/corridor-board listing)))

(defn- demand-rows []
  (mapv (fn [{:keys [rank iso units note in-table? omit-reason]}]
          [(str rank)
           (str (or (get-in border/markets [iso :label]) (name iso))
                " (" (name iso) ")")
           (catalog/grouped-int units)
           (if in-table? "見積対象" (str "除外: " (name (or omit-reason :n-a))))
           (str note)])
        (:rows border/jp-export-demand)))

(defn- procedure-rows [listing]
  (let [origin (border/origin-of listing)
        dests (map :landed/dest (border/quotes-from listing))
        dest (or (first (remove #{origin} dests)) origin)]
    (mapv (fn [{:keys [id label required?]}]
            [(name id) label (if required? "必須" "任意")])
          (border/procedure origin dest))))

(defn- detail-view [listing db]
  (let [c (catalog/card listing)
        vin (:vin listing)
        spec (:body-spec listing)
        cust (store/custody db vin)
        esc (first (filter #(= vin (:vin %)) (store/all-escrows db)))
        yen-gross (catalog/price-jpy listing)
        plan (when yen-gross (commerce/plan yen-gross))
        quotes (quote-rows listing)
        origin (border/origin-of listing)]
    [:section {:class "view" :id (str "view-" vin) :data-view (str "v/" vin)}
     (dds/heading 2 (:title c) {:size "32"})
     [:p {:class "price"} (:price c)]
     [:dl {:class "spec-dl"}
      (spec-row "年式" (:year c))
      (spec-row "走行距離" (:mileage c))
      (spec-row "国" (:country c))
      (spec-row "地域" (:prefecture c))
      (spec-row "ボディ" (:body c))
      (spec-row "燃料" (:fuel c))
      (spec-row "検査満了" (:inspection c))
      (spec-row "修復歴" (:repair-history c))
      (spec-row "ハンドル" (some-> (:steering listing) name))
      (spec-row "ドア / 定員" (when spec (str (:doors spec) " / " (:seats spec))))
      (spec-row "駆動" (:drive spec))
      (spec-row "車両重量" (:weight spec))
      (spec-row "寸法" (:size spec))
      (spec-row "出品者" (or (:owner-id listing) (:dealer listing)))
      (spec-row "出品区分" (cond (:demo? listing) "デモ在庫（販売対象外）"
                              (= :private-party (:listing-kind listing)) "自己申告の個人出品"
                              :else "販売店"))
      (spec-row "古物商許可" (:kobutsusho-license listing))
      (spec-row "販売免許" (:dealer-license listing))
      (spec-row "預かり" (some-> cust :status name))
      (spec-row "エスクロー" (or (some-> esc :status name) "未開設"))
      (spec-row "出品ID" vin)]
     (dds/heading 3 "カメラスキャン" {:size "24"})
     (into [:div {:class "scan-grid"}] (scan-cells listing))
     [:p {:class "muted"}
      "CID はデモラベル（bafkdemo-…）。実バイトは取得しない。"]
     (when (:running-cost listing)
       (list (dds/heading 3 "年間維持費（概算・日本）" {:size "24"})
             (dds/table {:headers ["費目" "円/年"]
                         :rows (cost-rows (:running-cost listing))})
             [:p {:class "muted"} (get-in listing [:running-cost :assumption])]))
     (dds/heading 3 "日本からの需要順（2025 輸出台数・二次集計）" {:size "24"})
     (dds/table {:headers ["順位" "仕向地" "台数" "適格" "関税概算" "注"]
                 :rows (corridor-rows listing)})
     [:p {:class "muted"}
      (str "出典 " (get-in border/jp-export-demand [:source])
           " as-of " (get-in border/jp-export-demand [:as-of])
           "。財務省の live extract ではない。ロシアは制裁リストが operator 入力のため市場表に載せない。")]
     (dds/heading 3 "国境手続（ラベル。通関申告はしない）" {:size "24"})
     [:p {:class "muted"}
      (str "出品国 " (name (or origin :na))
           "。下記は閉じた市場への概算。関税率は test-fixture "
           border/as-of "。HS は候補（未確定）。国境の賦課が正。")]
     (when (seq quotes)
       (dds/table {:headers ["仕向地" "HS候補" "CIF" "関税率" "関税" "VAT/GST" "概算合計"]
                   :rows quotes}))
     (dds/table {:headers ["手続" "内容" "要否"]
                 :rows (procedure-rows listing)})
     (dds/heading 3 "情報面 x402（車両代金ではない）" {:size "24"})
     (dds/table {:headers ["資源" "価格" "内容"] :rows (x402-rows)})
     [:p {:class "muted"}
      (str "facilitator " (get-in x402/facilitator [:host])
           " · 1 seller 精算プラン 手数料 "
           (:plan/commission-bps plan) " bps · execute? false")]
     [:div {:class "needs-serve"}
      (if (:demo? listing)
        [:p {:class "warn"}
         "この行はデモ在庫です。検索の見本であり、問い合わせ・取引の対象ではありません。実取引は登録した出品に対してのみ。"]
        (list
         (dds/heading 3 "問い合わせ" {:size "24"})
         [:form {:class "live-form" :id (str "inq-" vin) :data-live "inquiry" :data-vin vin}
          [:label "本文"
           [:input {:type "text" :name "body" :required true :minlength "2"
                    :placeholder "現車確認はできますか"}]]
          (dds/button "問い合わせる" {:submit? true :type :solid-fill})]
         (dds/heading 3 "取引の認可（送金しない）" {:size "24"})
         [:form {:class "live-form" :id (str "deal-" vin) :data-live "deal" :data-vin vin}
          [:p {:class "muted"}
           "エスクロー開設は認可だけです。代金の送金はこの面では実行しません。"]
          (dds/button "取引を認可する" {:submit? true :type :outline})]))]
     [:p {:class "muted needs-file"}
      "登録・問い合わせ・取引は `clojure -M:dev:serve` の live face で動きます。このファイル単体（file://）では検索の見本です。"]
     (dds/button "在庫一覧へ戻る" {:href "#search" :type :outline})]))

(defn- search-view [listings]
  (let [maker-opts (into [["" "メーカー（すべて）"]]
                         (map (fn [m] [m m]) (catalog/makers listings)))
        country-opts (into [["" "国（すべて）"]]
                           (map (fn [[k v]] [(name k) v]) catalog/countries))
        pref-opts (into [["" "地域（すべて）"]]
                        (map (fn [[k v]] [(name k) v]) catalog/prefectures))
        body-opts (into [["" "ボディ（すべて）"]]
                        (map (fn [[k v]] [(name k) v]) catalog/body-types))
        export-opts (into [["" "輸出先（日本ハブの需要順）"]]
                          (map (fn [iso]
                                 [(name iso) (get-in border/markets [iso :label] (name iso))])
                               (border/jp-demand-dests)))]
    [:section {:class "view is-active" :id "view-search" :data-view "search"}
     (dds/heading 2 "中古車を探す" {:size "32"})
     [:p {:class "muted"}
      (str "掲載 " (count listings)
           " 台。デモ在庫は検索の見本。実取引は登録した出品に対してのみ。"
           "代金の送金はこの面では実行しない。自己申告出品は電子車検証フィードではない。")]
     (dds/heading 3 "日本からの中古車輸出需要（2025）" {:size "24"})
     (dds/table {:headers ["順位" "仕向地" "台数" "この actor" "注"]
                 :rows (demand-rows)})
     [:p {:class "muted"}
      (str "総計 " (catalog/grouped-int (:total-units border/jp-export-demand))
           " 台。出典は JUMV の二次集計（" (:as-of border/jp-export-demand)
           "）。チリ本土の中古輸入は Ley 18.483 で禁止（ZOFRI再輸出が数量の本体）。南アの中古輸入は ITAC 許可制（ダーバン RIB 通過が数量の本体）。スリランカは製造3年（Gazette 2421/04）。タイは制度上閉じる。ロシアは載せない。")]
     [:form {:class "filter-row" :id "search-form" :action "#" :onsubmit "return false;"}
      [:label "キーワード"
       [:input {:type "search" :id "q" :name "q" :placeholder "メーカー・車種・国・地域"}]]
      [:label "メーカー" (dds/select {:id "make" :name "make" :value ""} maker-opts)]
      [:label "国" (dds/select {:id "country" :name "country" :value ""} country-opts)]
      [:label "輸出先" (dds/select {:id "export-dest" :name "export-dest" :value ""} export-opts)]
      [:label "地域" (dds/select {:id "prefecture" :name "prefecture" :value ""} pref-opts)]
      [:label "ボディ" (dds/select {:id "body" :name "body" :value ""} body-opts)]
      [:label "上限価格（万円・円換算）"
       [:input {:type "number" :id "price-max" :name "price-max" :min "0" :step "10"}]]
      [:label "上限走行（万km）"
       [:input {:type "number" :id "mileage-max" :name "mileage-max" :min "0" :step "1"}]]
      (dds/button "絞り込む" {:submit? true :type :solid-fill})]
     [:p {:class "muted" :id "result-count"}]
     (into [:div {:class "listing-grid" :id "listing-grid"}]
           (map card-el listings))]))

(defn- hold-rows [holds]
  (mapv (fn [{:keys [op subject basis violations]}]
          [(name (or op :n-a))
           (str subject)
           (str/join ", " (map name (or basis [])))
           (or (some :detail violations) "")])
        holds))

(defn- ledger-rows [ledger]
  (mapv (fn [{:keys [t op subject disposition basis]}]
          [(name (or t :n-a))
           (name (or op :n-a))
           (str subject)
           (or (some->> basis (map name) (str/join ", "))
               (some-> disposition name)
               "")])
        ledger))

(defn- inquiry-rows [db]
  (mapv (fn [{:keys [inquiry-id vin buyer-id body status]}]
          [(str inquiry-id) (str vin) (str buyer-id) (str body) (name (or status :n-a))])
        (store/all-inquiries db)))

(defn- escrow-rows [db]
  (mapv (fn [{:keys [escrow-id vin status gross-yen plan]}]
          [(str escrow-id) (str vin) (name (or status :n-a))
           (str (or gross-yen (get plan :plan/gross-yen)))
           (str (get plan :plan/seller-payout-yen))])
        (store/all-escrows db)))

(defn- custody-rows [db]
  (mapv (fn [v]
          (let [c (store/custody db (:vin v))]
            [(:vin v) (or (some-> c :status name) "—") (str (:holder c))]))
        (filter #(true? (:catalog? %)) (store/all-vehicles db))))

(defn- account-view []
  [:section {:class "view" :id "view-account" :data-view "account"}
   (dds/heading 2 "登録 / ログイン" {:size "32"})
   [:p {:class "muted needs-file"}
    "このページを動かすには `clojure -M:dev:serve`（既定 http://127.0.0.1:4510）。"]
   [:p {:id "whoami" :class "ok"}]
   [:form {:class "live-form needs-serve" :id "register-form" :data-live "register"}
    (dds/heading 3 "新規登録" {:size "24"})
    [:label "ハンドル（英小文字・数字・ハイフン）"
     [:input {:type "text" :name "handle" :required true :pattern "[a-z0-9][a-z0-9-]{1,30}"
              :autocomplete "username"}]]
    [:label "パスフレーズ（8文字以上）"
     [:input {:type "password" :name "password" :required true :minlength "8"
              :autocomplete "new-password"}]]
    [:label "役割"
     [:select {:name "role"}
      [:option {:value "buyer"} "買い手 / 個人出品"]
      [:option {:value "dealer-agent"} "販売店エージェント"]]]
    (dds/button "登録する" {:submit? true :type :solid-fill})]
   [:form {:class "live-form needs-serve" :id "login-form" :data-live "login"}
    (dds/heading 3 "ログイン" {:size "24"})
    [:label "ハンドル"
     [:input {:type "text" :name "handle" :required true :autocomplete "username"}]]
    [:label "パスフレーズ"
     [:input {:type "password" :name "password" :required true :autocomplete "current-password"}]]
    (dds/button "ログイン" {:submit? true :type :outline})]
   [:form {:class "live-form needs-serve" :id "logout-form" :data-live "logout"}
    (dds/button "ログアウト" {:submit? true :type :text})]])

(defn- inbox-view [db]
  (let [rows (mapv (fn [{:keys [inquiry-id vin buyer-id body status replies]}]
                     [(str inquiry-id) (str vin) (str buyer-id)
                      (str body) (name (or status :n-a))
                      (str (count (or replies [])))])
                   (store/all-inquiries db))]
    [:section {:class "view" :id "view-inbox" :data-view "inbox"}
     (dds/heading 2 "受信箱" {:size "32"})
     [:p {:class "muted"}
      "問い合わせは governor を通る。返信は買い手か出品者だけ。"]
     (if (seq rows)
       (dds/table {:headers ["ID" "車両" "買い手" "本文" "状態" "返信"]
                   :rows rows})
       [:p {:class "muted"} "問い合わせはまだ無い。"])
     [:form {:class "live-form needs-serve" :id "reply-form" :data-live "reply"}
      [:label "問い合わせID"
       [:input {:type "text" :name "inquiry-id" :required true}]]
      [:label "返信"
       [:input {:type "text" :name "body" :required true}]]
      (dds/button "返信する" {:submit? true :type :solid-fill})]]))

(defn- list-view []
  [:section {:class "view" :id "view-list" :data-view "list"}
   (dds/heading 2 "出品する" {:size "32"})
   [:p {:class "muted"}
    "個人出品は自己申告です。電子車検証フィードではありません。スキャンはデモラベルです。古物商の販売店出品はコンソール側のライセンス経路を使います。"]
   [:form {:class "live-form needs-serve" :id "list-form" :data-live "list"}
     [:label "出品ID（実VINを git に置かない。例 USER-1）"
     [:input {:type "text" :name "vin" :required true :pattern "[A-Za-z0-9][A-Za-z0-9-]{1,20}"}]]
    [:label "メーカー" [:input {:type "text" :name "make" :required true}]]
    [:label "車種" [:input {:type "text" :name "model" :required true}]]
    [:label "年式" [:input {:type "number" :name "year" :required true :min "1980" :max "2026"}]]
    [:label "価格（円）" [:input {:type "number" :name "price" :required true :min "1"}]]
    [:label "走行距離（km）" [:input {:type "number" :name "mileage" :required true :min "0"}]]
    [:label "都道府県"
     [:select {:name "prefecture"}
      [:option {:value "tokyo"} "東京都"]
      [:option {:value "osaka"} "大阪府"]
      [:option {:value "aichi"} "愛知県"]
      [:option {:value "fukuoka"} "福岡県"]
      [:option {:value "hokkaido"} "北海道"]]]
    [:label "ボディ"
     [:select {:name "body-type"}
      [:option {:value "sedan"} "セダン"]
      [:option {:value "hatch"} "ハッチバック"]
      [:option {:value "suv"} "SUV"]
      [:option {:value "minivan"} "ミニバン"]]]
    (dds/button "出品する" {:submit? true :type :solid-fill})]])

(defn- operator-view [db]
  (let [holds (hold-facts db)
        ledger (store/ledger db)
        inquiries (inquiry-rows db)
        escrows (escrow-rows db)]
    [:section {:class "view" :id "view-operator" :data-view "operator"}
     (dds/heading 2 "出品コンソール（Governor）" {:size "32"})
     [:p {:class "muted"}
      "VehicleSale-LLM の提案は VehicleSaleGovernor を通ったものだけが台帳に残る。HARD hold は人間も覆せない。マネー操作と輸出入証明は常に人間承認。送金しない。通関申告しない。"]
     (dds/heading 3 "HARD hold（この run）" {:size "24"})
     (dds/table {:headers ["操作" "対象" "規則" "詳細"]
                 :rows (hold-rows holds)
                 :row-header? true})
     (dds/heading 3 "問い合わせ（lead）" {:size "24"})
     (if (seq inquiries)
       (dds/table {:headers ["ID" "車両" "buyer-id" "本文" "状態"]
                   :rows inquiries})
       [:p {:class "muted"} "問い合わせはまだ無い。"])
     (dds/heading 3 "エスクロー（認可。execute? false）" {:size "24"})
     (if (seq escrows)
       (dds/table {:headers ["ID" "VIN" "状態" "総額" "出品者払出"]
                   :rows escrows})
       [:p {:class "muted"} "エスクローはまだ無い。"])
     (dds/heading 3 "車両の預かり" {:size "24"})
     (dds/table {:headers ["VIN" "状態" "ホルダ"]
                 :rows (custody-rows db)})
     (dds/heading 3 "監査台帳" {:size "24"})
     (dds/table {:headers ["事実" "操作" "対象" "根拠"]
                 :rows (ledger-rows ledger)})]))

(def ^:private spa-js
  "function showView(name){
  document.querySelectorAll('.view').forEach(function(el){
    el.classList.toggle('is-active', el.getAttribute('data-view')===name);
  });
}
function applyHash(){
  var h=(location.hash||'#search').replace(/^#/,'');
  if(!h) h='search';
  var target=document.querySelector('[data-view=\"'+h+'\"]');
  showView(target?h:'search');
}
function applyFilters(){
  var q=(document.getElementById('q').value||'').toLowerCase();
  var make=document.getElementById('make').value;
  var country=document.getElementById('country') && document.getElementById('country').value;
  var ex=document.getElementById('export-dest') && document.getElementById('export-dest').value;
  var pref=document.getElementById('prefecture').value;
  var body=document.getElementById('body').value;
  var pmax=document.getElementById('price-max').value;
  var mmax=document.getElementById('mileage-max').value;
  var n=0;
  document.querySelectorAll('#listing-grid .listing-card').forEach(function(card){
    var ok=true;
    if(make && card.getAttribute('data-make')!==make) ok=false;
    if(country && card.getAttribute('data-country')!==country) ok=false;
    if(ex){
      var toks=(card.getAttribute('data-export')||'').split(',');
      if(toks.indexOf(ex)<0) ok=false;
    }
    if(pref && card.getAttribute('data-prefecture')!==pref) ok=false;
    if(body && card.getAttribute('data-body')!==body) ok=false;
    if(pmax && Number(card.getAttribute('data-price'))>Number(pmax)*10000) ok=false;
    if(mmax && Number(card.getAttribute('data-mileage'))>Number(mmax)*10000) ok=false;
    if(q && (card.getAttribute('data-q')||'').toLowerCase().indexOf(q)<0) ok=false;
    card.classList.toggle('is-hidden', !ok);
    if(ok) n++;
  });
  var el=document.getElementById('result-count');
  if(el) el.textContent=n+' 件';
}
function ednStr(s,k){
  var needle=':'+k+' \"';
  var i=String(s).indexOf(needle);
  if(i<0) return null;
  var rest=String(s).slice(i+needle.length);
  var end=rest.indexOf('\"');
  return end<0?null:rest.slice(0,end);
}
function ednOk(s){ return /:ok true/.test(String(s)); }
function token(){ return sessionStorage.getItem('itonami-4510-token'); }
function setToken(t){ if(t) sessionStorage.setItem('itonami-4510-token', t); }
function api(path, form){
  var headers={'Accept':'application/edn'};
  var t=token();
  if(t) headers['Authorization']='Bearer '+t;
  var opts={method: form?'POST':'GET', headers:headers, credentials:'same-origin'};
  if(form){
    headers['Content-Type']='application/x-www-form-urlencoded';
    opts.body=new URLSearchParams(new FormData(form)).toString();
  }
  return fetch(path, opts).then(function(r){
    return r.text().then(function(text){ return {ok:r.ok, text:text, status:r.status}; });
  });
}
function flash(text){
  var el=document.getElementById('live-flash');
  if(el) el.textContent=text;
}
function bindLiveForms(){
  document.querySelectorAll('form[data-live]').forEach(function(form){
    form.addEventListener('submit', function(e){
      e.preventDefault();
      var kind=form.getAttribute('data-live');
      var path={register:'/api/register',login:'/api/login',logout:'/api/logout',
                inquiry:'/api/inquiry',reply:'/api/reply',list:'/api/list',deal:'/api/deal'}[kind];
      if(kind==='inquiry' || kind==='deal'){
        var vin=form.getAttribute('data-vin');
        var extra=document.createElement('input');
        extra.type='hidden'; extra.name='vin'; extra.value=vin;
        form.appendChild(extra);
      }
      api(path, form).then(function(res){
        var tok=ednStr(res.text,'token');
        if(tok) setToken(tok);
        if(ednOk(res.text) || res.ok){
          if(kind==='logout'){ sessionStorage.removeItem('itonami-4510-token'); }
          flash('ok');
          location.hash = (kind==='register'||kind==='login') ? '#inbox' : (kind==='list' ? '#search' : location.hash);
          location.reload();
        } else {
          flash(res.text || ('error '+res.status));
        }
      }).catch(function(err){ flash(String(err)); });
    });
  });
}
function bootLive(){
  fetch('/api/health').then(function(r){
    if(!r.ok) throw new Error('no api');
    document.body.classList.add('is-live');
    document.querySelectorAll('.needs-serve').forEach(function(el){ el.hidden=false; });
    document.querySelectorAll('.needs-file').forEach(function(el){ el.hidden=true; });
    bindLiveForms();
    return api('/api/me');
  }).then(function(res){
    if(!res) return;
    var h=ednStr(res.text,'handle');
    var el=document.getElementById('whoami');
    if(el && h) el.textContent='ログイン中: '+h;
  }).catch(function(){
    document.querySelectorAll('.needs-serve').forEach(function(el){ el.hidden=true; });
    document.querySelectorAll('.needs-file').forEach(function(el){ el.hidden=false; });
  });
}
window.addEventListener('hashchange', applyHash);
document.addEventListener('DOMContentLoaded', function(){
  applyHash();
  var form=document.getElementById('search-form');
  if(form){
    form.addEventListener('submit', function(e){ e.preventDefault(); applyFilters(); });
    form.addEventListener('change', applyFilters);
    form.addEventListener('input', applyFilters);
    applyFilters();
  }
  bootLive();
});")

(defn render
  [db]
  (let [all (listings db)
        hits (catalog/search all {})]
    (page/->page
     {:title "中古車マーケット — cloud-itonami-isic-4510"
      :description "ISIC 4510 の中古車出品検索。日本ハブ。需要の高い仕向地から適格判定する。"
      :lang "ja"
      :css (slurp (io/resource "jp_go_dds/dds.css"))
      :app-css app-css
      :head [[:script spa-js]]}
     (dds/container
      [:header
       (dds/heading 1 "中古車マーケット" {:size "45"})
       [:p {:class "muted"}
        "cloud-itonami-isic-4510 · 日本の在庫を中心に、需要の高い仕向地から適格判定する。送金しない。通関申告しない。デモ在庫は販売しない。"]
       [:p {:id "live-flash" :class "ok"}]]
      [:nav {:class "site-nav" :aria-label "ページ内"}
       (dds/button "在庫を探す" {:href "#search" :type :solid-fill})
       (dds/button "登録" {:href "#account" :type :outline})
       (dds/button "受信箱" {:href "#inbox" :type :outline})
       (dds/button "出品する" {:href "#list" :type :outline})
       (dds/button "出品コンソール" {:href "#operator" :type :outline})]
      (search-view hits)
      (into [:div] (map #(detail-view % db) hits))
      (account-view)
      (inbox-view db)
      (list-view)
      (operator-view db)
      [:footer
       [:p {:class "muted"}
        "build-time 生成、または `clojure -M:dev:serve` の live face。Governor を通らない書込は無い。execute? false。"]]))))

(defn- assert-demo! [db]
  (let [holds (hold-facts db)
        seen (exercised-hard-rules db)
        missing (set/difference policy/hard-rule-ids seen)]
    (when (empty? holds)
      (throw (ex-info "no :policy-hold fact on the ledger — refusing to write a console that shows no real hold"
                      {:ledger-facts (count (store/ledger db))})))
    (when (seq missing)
      (throw (ex-info "declared HARD rule silent in this run — refusing to write a partial console"
                      {:missing missing :seen seen})))
    (when (empty? (store/all-inquiries db))
      (throw (ex-info "no inquiry landed — marketplace lead path was not exercised"
                      {})))
    (when-not (= :sold (:listed-status (store/vehicle db "JP-400")))
      (throw (ex-info "JP-400 was not marked sold after disclosed confirm"
                      {:vehicle (store/vehicle db "JP-400")})))))

(defn -main [& args]
  (let [out (or (first args) "docs/samples/operator-console.html")
        db (run-demo!)]
    (assert-demo! db)
    (let [html (render db)
          f (io/file out)
          index (io/file "docs/index.html")]
      (when-let [p (.getParentFile f)] (.mkdirs p))
      (spit f html)
      (when-not (= (.getCanonicalPath f) (.getCanonicalPath index))
        (spit index html))
      (println "wrote" out "and docs/index.html"
               (str "(" (count (store/ledger db)) " ledger facts, "
                    (count (hold-facts db)) " HARD holds, "
                    (count (store/all-inquiries db)) " inquiries)")))))
