(ns vehiclesale.render-html
  "Build-time SPA for the used-car marketplace (Carsensor-like search) plus
  the operator console. One document, fragment views (`#search` / `#v/<vin>`
  / `#operator`). Generated by driving the real OperationActor
  (VehicleSale-LLM ⊣ VehicleSaleGovernor ⊣ store).

  Usage: `clojure -M:dev:render-html [out-file]`
  Default writes `docs/samples/operator-console.html` and also `docs/index.html`
  (same bytes — one SPA, two entry paths)."
  (:require [clojure.java.io :as io]
            [clojure.set :as set]
            [clojure.string :as str]
            [jp-go-dds.core :as dds]
            [jp-go-dds.page :as page]
            [jp-go-dds.tokens :as tokens]
            [langgraph.graph :as g]
            [vehiclesale.catalog :as catalog]
            [vehiclesale.operation :as op]
            [vehiclesale.policy :as policy]
            [vehiclesale.store :as store]))

(def ^:private dealer {:actor-id "da-1" :actor-role :dealer-agent :phase 3})
(def ^:private buyer {:actor-id "b-1" :actor-role :buyer :tenant "tenant-basic" :phase 3})

(def jp-airis
  {:class :operator-licensed-shakensho-feed
   :ref "airis-demo:JP-100"
   :license-id "airis-demo"})

(defn- exec! [actor tid request context]
  (g/run* actor {:request request :context context} {:thread-id tid}))

(defn- approve! [actor tid]
  (g/run* actor {:approval {:status :approved :by "officer-1"}}
          {:thread-id tid :resume? true}))

(defn- jp-list
  [vin extra]
  (let [seed (get-in (store/demo-data) [:vehicles vin])]
    (merge {:op :vehicle/list :subject vin :vin vin
            :source (assoc jp-airis :ref (str "airis-demo:" vin))}
           seed
           extra)))

(defn run-demo!
  "Fresh seed through a mix of marketplace writes and every HARD gate.
  Returns the store. Every field the page reads comes from this run."
  []
  (let [db (store/seed-db)
        actor (op/build db)]
    ;; US: authorized listing commits (odometer bump).
    (exec! actor "us-list"
           {:op :vehicle/list :subject "vin-100" :vin "vin-100" :make "Demo"
            :model "Sedan" :year 2022 :title-status :clean :price 18500.00M
            :odometer 33500 :state :ca
            :source {:class :federal-title-registry :ref "nmvtis-doj-gateway:vin-100"}}
           dealer)
    ;; HARD: rbac
    (exec! actor "rbac"
           {:op :vehicle/list :subject "vin-100" :vin "vin-100" :make "Demo"
            :model "Sedan" :year 2022 :title-status :clean :price 18500.00M
            :odometer 33600 :state :ca
            :source {:class :federal-title-registry :ref "nmvtis-doj-gateway:vin-100"}}
           buyer)
    ;; HARD: source-provenance (unsourced)
    (exec! actor "unsourced"
           {:op :vehicle/list :subject "vin-100" :vin "vin-100" :make "Demo"
            :model "Sedan" :year 2022 :title-status :clean :price 18500.00M
            :odometer 33700 :state :ca
            :source {:class :federal-title-registry :ref "demo"} :unsourced? true}
           dealer)
    ;; HARD: lien-clearance
    (exec! actor "lien"
           {:op :sale/confirm :subject "vin-200" :vin "vin-200"
            :lien-cleared? false :odometer-disclosure-statement? true}
           dealer)
    ;; HARD: licensed-disclosure
    (exec! actor "greedy"
           {:op :disclosure/query :subject "vin-100" :vin "vin-100" :greedy? true}
           buyer)
    ;; HARD: odometer rollback
    (exec! actor "rollback"
           {:op :vehicle/list :subject "vin-300" :vin "vin-300" :make "Demo"
            :model "Hatchback" :year 2019 :title-status :salvage :price 6200.00M
            :odometer 50000 :state :ca
            :source {:class :federal-title-registry :ref "nmvtis-doj-gateway:vin-300"}}
           dealer)
    ;; HARD: 古物商許可欠落
    (exec! actor "no-kobutsusho"
           (jp-list "JP-100" {:kobutsusho-license "" :odometer 32100})
           dealer)
    ;; HARD: 修復歴未開示
    (exec! actor "no-repair-hist"
           {:op :sale/confirm :subject "JP-400" :vin "JP-400" :lien-cleared? true}
           dealer)
    ;; HARD: inquiry against missing VIN
    (exec! actor "ghost-inq"
           {:op :inquiry/submit :subject "JP-ghost" :vin "JP-ghost"
            :buyer-id "buyer-demo" :body "この車の現車確認はできますか" :inquiry-id "inq-ghost"}
           buyer)
    ;; JP listing commit ( legit 古物商 + AIRIS )
    (exec! actor "jp-list"
           (jp-list "JP-100" {:odometer 32100})
           dealer)
    ;; buyer inquiry commit
    (exec! actor "jp-inq"
           {:op :inquiry/submit :subject "JP-200" :vin "JP-200"
            :buyer-id "buyer-demo" :body "試乗希望です" :inquiry-id "inq-JP-200"}
           buyer)
    ;; JP sale with 修復歴 disclosed → sold
    (exec! actor "jp-sold"
           {:op :sale/confirm :subject "JP-400" :vin "JP-400"
            :lien-cleared? true :repair-history-disclosed? false}
           dealer)
    ;; salvage US sale escalates then human approves
    (let [r (exec! actor "salvage"
                    {:op :sale/confirm :subject "vin-300" :vin "vin-300"
                     :lien-cleared? true :odometer-disclosure-statement? true}
                    dealer)]
      (when (= :interrupted (:status r))
        (approve! actor "salvage")))
    db))

(defn- listings [db]
  (mapv (fn [v]
          (catalog/hydrate v (store/odometer-latest db (:vin v))
                           (store/title-record db (:vin v))))
        (store/all-vehicles db)))

(defn- hold-facts [db]
  (filterv #(= :policy-hold (:t %)) (store/ledger db)))

(defn- exercised-hard-rules [db]
  (into #{} (mapcat :basis (hold-facts db))))

(def ^:private app-css
  (str tokens/bridge-css "\n" tokens/a11y-css "\n"
       (str/join "\n"
                 [".site-nav{display:flex;gap:0.5rem;flex-wrap:wrap;margin:0 0 1.5rem}"
                  ".view{display:none}"
                  ".view.is-active{display:block}"
                  ".listing-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(16rem,1fr));gap:1rem}"
                  ".listing-card{display:block;text-decoration:none;color:inherit}"
                  ".listing-card .price{font-size:1.25rem;font-weight:700;color:var(--color-key-900)}"
                  ".listing-card .meta{color:var(--color-neutral-solid-gray-600);font-size:0.875rem}"
                  ".listing-card.is-hidden{display:none}"
                  ".spec-dl{display:grid;grid-template-columns:8rem 1fr;gap:0.25rem 1rem}"
                  ".spec-dl dt{color:var(--color-neutral-solid-gray-600)}"
                  ".filter-row{display:flex;flex-wrap:wrap;gap:0.75rem;align-items:flex-end;margin:0 0 1rem}"
                  ".filter-row label{display:flex;flex-direction:column;font-size:0.875rem;gap:0.25rem}"
                  ".muted{color:var(--color-neutral-solid-gray-600)}"
                  ".ok{color:var(--color-success-900,#0b7a3b)}"
                  ".critical{color:var(--color-error-900,#c52828)}"
                  ".warn{color:var(--color-warning-900,#8a5a00)}"])))

(defn- card-el [listing]
  (let [c (catalog/card listing)]
    [:a {:class "listing-card dds-ext-card"
         :href (:href c)
         :data-vin (:vin listing)
         :data-make (:make listing)
         :data-prefecture (some-> (:prefecture listing) name)
         :data-year (str (:year listing))
         :data-price (str (long (:price listing)))
         :data-mileage (str (:mileage listing))
         :data-body (some-> (:body-type listing) name)
         :data-q (str (:make listing) " " (:model listing) " " (:grade listing) " "
                      (get catalog/prefectures (:prefecture listing)))}
     (dds/heading 3 (:title c) {:size "20"})
     [:p {:class "price"} (:price c)]
     [:p {:class "meta"}
      (str (:year c) " · " (:mileage c) " · " (:prefecture c))]
     [:p {:class "meta"}
      (str (:body c) " · " (:fuel c) " · " (:repair-history c))]
     [:p {:class "meta"} (:dealer c)]]))

(defn- spec-row [k v]
  (when v
    (list [:dt k] [:dd (str v)])))

(defn- detail-view [listing]
  (let [c (catalog/card listing)
        vin (:vin listing)]
    [:section {:class "view" :id (str "view-" vin) :data-view (str "v/" vin)}
     (dds/heading 2 (:title c) {:size "32"})
     [:p {:class "price"} (:price c)]
     [:dl {:class "spec-dl"}
      (spec-row "年式" (:year c))
      (spec-row "走行距離" (:mileage c))
      (spec-row "地域" (:prefecture c))
      (spec-row "ボディ" (:body c))
      (spec-row "燃料" (:fuel c))
      (spec-row "車検" (:inspection c))
      (spec-row "修復歴" (:repair-history c))
      (spec-row "販売店" (:dealer listing))
      (spec-row "古物商許可" (:kobutsusho-license listing))
      (spec-row "出品ID" vin)]
     (dds/button "販売店へ問い合わせる（デモ）" {:href "#operator" :type :solid-fill})
     [:p {:class "muted"}
      "問い合わせは VehicleSaleGovernor を通る。決済・エスクロー・車両の引き渡しはこの actor の外。"]
     (dds/button "在庫一覧へ戻る" {:href "#search" :type :outline})]))

(defn- search-view [jp-listings]
  (let [maker-opts (into [["" "メーカー（すべて）"]]
                         (map (fn [m] [m m]) (catalog/makers jp-listings)))
        pref-opts (into [["" "地域（すべて）"]]
                        (map (fn [[k v]] [(name k) v]) catalog/prefectures))
        body-opts (into [["" "ボディ（すべて）"]]
                        (map (fn [[k v]] [(name k) v]) catalog/body-types))]
    [:section {:class "view is-active" :id "view-search" :data-view "search"}
     (dds/heading 2 "中古車を探す" {:size "32"})
     [:p {:class "muted"}
      (str "掲載 " (count jp-listings)
           " 台。架空のデモ在庫です。実在の車両・販売店ではありません。")]
     [:form {:class "filter-row" :id "search-form" :action "#" :onsubmit "return false;"}
      [:label "キーワード"
       [:input {:type "search" :id "q" :name "q" :placeholder "メーカー・車種・地域"}]]
      [:label "メーカー" (dds/select {:id "make" :name "make" :value ""} maker-opts)]
      [:label "地域" (dds/select {:id "prefecture" :name "prefecture" :value ""} pref-opts)]
      [:label "ボディ" (dds/select {:id "body" :name "body" :value ""} body-opts)]
      [:label "上限価格（万円）"
       [:input {:type "number" :id "price-max" :name "price-max" :min "0" :step "10"}]]
      [:label "上限走行（万km）"
       [:input {:type "number" :id "mileage-max" :name "mileage-max" :min "0" :step "1"}]]
      (dds/button "絞り込む" {:submit? true :type :solid-fill})]
     [:p {:class "muted" :id "result-count"}]
     (into [:div {:class "listing-grid" :id "listing-grid"}]
           (map card-el jp-listings))]))

(defn- hold-rows [holds]
  (mapv (fn [{:keys [op subject basis violations]}]
          [(name (or op :n-a))
           (str subject)
           (str/join ", " (map name (or basis [])))
           (or (some :detail violations) "")])
        holds))

(defn- ledger-rows [ledger]
  (mapv (fn [{:keys [t op subject disposition basis]}]
          [(name (or t :n-a))
           (name (or op :n-a))
           (str subject)
           (or (some->> basis (map name) (str/join ", "))
               (some-> disposition name)
               "")])
        ledger))

(defn- inquiry-rows [db]
  (mapv (fn [{:keys [inquiry-id vin buyer-id body status]}]
          [(str inquiry-id) (str vin) (str buyer-id) (str body) (name (or status :n-a))])
        (store/all-inquiries db)))

(defn- operator-view [db]
  (let [holds (hold-facts db)
        ledger (store/ledger db)
        inquiries (inquiry-rows db)]
    [:section {:class "view" :id "view-operator" :data-view "operator"}
     (dds/heading 2 "出品コンソール（Governor）" {:size "32"})
     [:p {:class "muted"}
      "VehicleSale-LLM の提案は VehicleSaleGovernor を通ったものだけが台帳に残る。HARD hold は人間も覆せない。"]
     (dds/heading 3 "HARD hold（この run）" {:size "24"})
     (dds/table {:headers ["操作" "対象" "規則" "詳細"]
                 :rows (hold-rows holds)
                 :row-header? true})
     (dds/heading 3 "問い合わせ（lead。決済ではない）" {:size "24"})
     (if (seq inquiries)
       (dds/table {:headers ["ID" "車両" "buyer-id" "本文" "状態"]
                   :rows inquiries})
       [:p {:class "muted"} "問い合わせはまだ無い。"])
     (dds/heading 3 "監査台帳" {:size "24"})
     (dds/table {:headers ["事実" "操作" "対象" "根拠"]
                 :rows (ledger-rows ledger)})]))

(def ^:private spa-js
  "function showView(name){
  document.querySelectorAll('.view').forEach(function(el){
    el.classList.toggle('is-active', el.getAttribute('data-view')===name);
  });
}
function applyHash(){
  var h=(location.hash||'#search').replace(/^#/,'');
  if(!h) h='search';
  var target=document.querySelector('[data-view=\"'+h+'\"]');
  showView(target?h:'search');
}
function applyFilters(){
  var q=(document.getElementById('q').value||'').toLowerCase();
  var make=document.getElementById('make').value;
  var pref=document.getElementById('prefecture').value;
  var body=document.getElementById('body').value;
  var pmax=document.getElementById('price-max').value;
  var mmax=document.getElementById('mileage-max').value;
  var n=0;
  document.querySelectorAll('#listing-grid .listing-card').forEach(function(card){
    var ok=true;
    if(make && card.getAttribute('data-make')!==make) ok=false;
    if(pref && card.getAttribute('data-prefecture')!==pref) ok=false;
    if(body && card.getAttribute('data-body')!==body) ok=false;
    if(pmax && Number(card.getAttribute('data-price'))>Number(pmax)*10000) ok=false;
    if(mmax && Number(card.getAttribute('data-mileage'))>Number(mmax)*10000) ok=false;
    if(q && (card.getAttribute('data-q')||'').toLowerCase().indexOf(q)<0) ok=false;
    card.classList.toggle('is-hidden', !ok);
    if(ok) n++;
  });
  var el=document.getElementById('result-count');
  if(el) el.textContent=n+' 件';
}
window.addEventListener('hashchange', applyHash);
document.addEventListener('DOMContentLoaded', function(){
  applyHash();
  var form=document.getElementById('search-form');
  if(form){
    form.addEventListener('submit', function(e){ e.preventDefault(); applyFilters(); });
    form.addEventListener('change', applyFilters);
    form.addEventListener('input', applyFilters);
    applyFilters();
  }
});")

(defn render
  [db]
  (let [all (listings db)
        jp (catalog/search all {})]
    (page/->page
     {:title "中古車マーケット — cloud-itonami-isic-4510"
      :description "ISIC 4510 の中古車出品検索。VehicleSaleGovernor が出品・成約・問い合わせを検閲する。"
      :lang "ja"
      :css (slurp (io/resource "jp_go_dds/dds.css"))
      :app-css app-css
      :head [[:script spa-js]]}
     (dds/container
      [:header
       (dds/heading 1 "中古車マーケット" {:size "45"})
       [:p {:class "muted"}
        "cloud-itonami-isic-4510 · 出品・開示・成約決定。決済と車両の保管は持たない。"]]
      [:nav {:class "site-nav" :aria-label "ページ内"}
       (dds/button "在庫を探す" {:href "#search" :type :solid-fill})
       (dds/button "出品コンソール" {:href "#operator" :type :outline})]
      (search-view jp)
      (into [:div] (map detail-view jp))
      (operator-view db)
      [:footer
       [:p {:class "muted"}
        "build-time 生成: vehiclesale.render-html が実 actor を seed に対して走らせた結果。時計・乱数・ネットワークは使っていない。"]]))))

(defn- assert-demo! [db]
  (let [holds (hold-facts db)
        seen (exercised-hard-rules db)
        missing (set/difference policy/hard-rule-ids seen)]
    (when (empty? holds)
      (throw (ex-info "no :policy-hold fact on the ledger — refusing to write a console that shows no real hold"
                      {:ledger-facts (count (store/ledger db))})))
    (when (seq missing)
      (throw (ex-info "declared HARD rule silent in this run — refusing to write a partial console"
                      {:missing missing :seen seen})))
    (when (empty? (store/all-inquiries db))
      (throw (ex-info "no inquiry landed — marketplace lead path was not exercised"
                      {})))
    (when-not (= :sold (:listed-status (store/vehicle db "JP-400")))
      (throw (ex-info "JP-400 was not marked sold after disclosed confirm"
                      {:vehicle (store/vehicle db "JP-400")})))))

(defn -main [& args]
  (let [out (or (first args) "docs/samples/operator-console.html")
        db (run-demo!)]
    (assert-demo! db)
    (let [html (render db)
          f (io/file out)
          index (io/file "docs/index.html")]
      (when-let [p (.getParentFile f)] (.mkdirs p))
      (spit f html)
      (when-not (= (.getCanonicalPath f) (.getCanonicalPath index))
        (spit index html))
      (println "wrote" out "and docs/index.html"
               (str "(" (count (store/ledger db)) " ledger facts, "
                    (count (hold-facts db)) " HARD holds, "
                    (count (store/all-inquiries db)) " inquiries)")))))
